{
    'name': 'ISD PhotoBooth',
    'version': '18.0.1.0.0',
    'category': 'ISD Modules',
    'summary': 'Photo Booth Management System',
    'author': 'IntelliSync Data',
    'website': 'https://intellisyncdata.com',
    'license': 'LGPL-3',
    'depends': ['base', 'base_setup', 'mail'],
    'data': [
        'security/isd_photobooth_security.xml',
        'security/ir.model.access.csv',
        'views/isd_photobooth_group_views.xml',
        'views/isd_photobooth_background_views.xml',
        'views/isd_photobooth_theme_views.xml',
        'views/isd_photobooth_layout_views.xml',
        'views/isd_photobooth_layout_system_type_views.xml',
        'views/isd_photobooth_views.xml',
        'views/isd_photobooth_transaction_views.xml',
        'views/isd_photobooth_promo_code_views.xml',
        'views/isd_photobooth_promotion_views.xml',
        'views/isd_photobooth_audit_log_views.xml',
        'views/isd_photobooth_ticket_views.xml',
        'views/isd_photobooth_app_version_views.xml',
        'views/isd_photobooth_api_reference_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'isd_photobooth/static/src/js/api_reference.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
